### ISSUE TITLE
Error when starting

### ISSUE THREAD

**Issue by eugenikus8** [drdozer/transport-drones-on-asphalt#1]
![2022-07-19_201211](https://user-images.githubusercontent.com/51211736/179809928-8e944b47-6a70-49b3-bc3c-76a67c6c3a98.png)

**Comment by eugenikus8** [comment]
In version 0.1.1, the problem is solved

**Comment by drdozer** [comment]
Glad it magically fixed itself :) I'm marking as closed.

**Comment by drdozer** [comment]
ugg - still getting used to the newer github workflows...
